version: "3.8"
services:
  app:
    image: golang:1.16.5-alpine
    volumes: 
        - .:/go/src/go-url-shortener
    working_dir: /go/src/go-url-shortener
    command: go run main.go
    ports:
      - "9888:9888"
    links: 
        - redis
    environment:
        REDIS_URL: redis:6379
  redis:
    image: redis:6.2.4-alpine
    ports:
      - "6379:6379"
